[package]
name = "atlasr-api-tile"
version = "0.1.0"
authors = ["Ivan Enderlin <ivan.enderlin@hoa-project.net>"]

[dependencies]
warp = "^0.1.9"
diesel = { version = "^1.3.3", features = ["sqlite"] }
r2d2 = "^0.8.3"
r2d2-diesel = "^1.0.0"