[package]
name = "atlasr-api-geocode-searcher"
version = "0.1.0"
authors = ["Ivan Enderlin <ivan.enderlin@hoa-project.net>"]

[dependencies]
tantivy = { git = "https://github.com/tantivy-search/tantivy", branch = "master" }
actix-web = "^0.6.10"