[package]
name = "atlasr-server"
version = "0.0.1"
authors = ["Ivan Enderlin <ivan.enderlin@hoa-project.net>"]

[dependencies]
futures = "^0.1.14"
hyper = "^0.11.2"
mime = "^0.3.5"
regex = "^0.2.5"
lazy_static = "^1.0"